builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - format: binary
dockers:
  - image_templates:
      - 'ghcr.io/simonswine/covid-thanos-store:latest'
      - 'ghcr.io/simonswine/covid-thanos-store:{{ .Tag }}'
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: sha256sums.txt
snapshot:
  name_template: '{{ .Tag }}-dev'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
